on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: "ibkbd-mini/zmk/build.yaml"
      config_path: "ibkbd-mini/zmk/config"
