on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: echo "ZEPHYR_BASE=${{ github.workspace }}/ibkbd-mini/zmk/zephyr" >> $GITHUB_ENV

      - name: Run ZMK build workflow
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
        with:
          build_matrix_path: "ibkbd-mini/zmk/build.yaml"
          config_path: "ibkbd-mini/zmk/config"
